# netlify.toml
[build]
  # 1) Your build command (CRA default, Vite default, etc)
  command   = "npm run build"
  # 2) The folder Netlify should publish as your site
  publish   = "build"        # if you're using create-react-app
  # publish = "dist"         # if you're using Vite

  # 3) Where your Functions live
  functions = "netlify/functions"
